export const OfferCardStyles = {
  Card: "rounded-2xl shadow-lg overflow-hidden flex flex-col bg-white w-full xm:w-[95%] sm:w-[90%] md:w-[558px] max-w-[95vw] min-h-[213px]",
  CardTop: "flex flex-col sm:flex-row p-3 sm:p-4 gap-3 sm:gap-4 items-start bg-[#FAF6F6] flex-1",
  Row: "flex flex-col sm:flex-row w-full gap-2 sm:gap-4",
  LogoDiv: "flex flex-col justify-start items-start sm:pr-4 mt-2 sm:mt-3",
  Logo: "w-[4rem] h-[4rem] sm:w-20 sm:h-20 rounded-full object-contain max-w-full max-h-full",
  CardContentRow: "flex flex-col flex-1",
  CardContent: "flex flex-col flex-1",
  DateText: "text-sm sm:text-[1rem] text-[#3C3C43] font-mono",
  TitleText: "text-base xm:text-[1.25rem] sm:text-[1.5rem] font-mono font-bold text-black leading-tight",
  CompanyText: "text-sm xm:text-[1.125rem] text-[#3C3C43]",
  LocationText: "text-sm xm:text-[1.125rem] text-[#0353A4] font-mono",
  FavoriteIcon: "w-[20px] h-[20px] ml-auto cursor-pointer hidden sm:block",
  TagsRow: "flex flex-wrap gap-2 w-full",
  CategoryTag: "rounded-[100px] bg-[#3C3C43] px-3 py-1 text-sm sm:text-md text-white font-mono",
  CriticalTag: "rounded-[100px] border border-[#FF3D00] px-3 py-1 text-sm sm:text-md text-[#FF3D00] font-mono",
  CommonTag: "rounded-[100px] border border-[#3C3C43] px-3 py-1 text-sm sm:text-md text-[#3C3C43] font-mono",
  CardBottom: "flex flex-col sm:flex-row flex-wrap items-center justify-start sm:justify-between bg-[#D9D9D9] px-3 py-2 gap-2 w-full",
  HideButton: "flex items-center gap-2 text-[#FF3D00] px-3 py-1 rounded-lg font-mono text-sm font-semibold cursor-pointer",
  HideIcon: "w-[20px] h-[20px]",
  AddApplicationButton: "flex items-center justify-center gap-2 bg-[#0353A4] text-white w-full sm:w-auto px-3 py-1.5 rounded-lg font-mono text-sm font-semibold cursor-pointer",
  AddIcon: "w-[20px] h-[20px]",
  ApplyButton: "flex items-center justify-center gap-2 bg-white text-[#0353A4] w-full sm:w-auto px-3 py-1.5 rounded-lg font-mono text-sm font-semibold cursor-pointer",
  ApplyIcon: "w-[20px] h-[20px]",
  GroupedButtons: "flex flex-col sm:flex-row gap-2 sm:gap-3 w-full sm:w-auto"
};
