export const OfferCardStyles = {
    Card: "rounded-2xl shadow-lg overflow-hidden flex flex-col bg-white w-[90vw] sm:w-[420px] md:w-[558px] max-w-full min-h-[213px]",
    CardTop: "flex flex-row p-4 sm:p-5 gap-4 items-start bg-[#FAF6F6] flex-1",
    Row:"flex flex-row w-full",
    LogoDiv:"flex flex-col justify-start items-start pr-4 mt-3",
    Logo: "w-[5rem] h-[5rem] sm:w-20 sm:h-20 rounded-full object-contain max-w-full max-h-full",
    CardContentRow:"flex flex-col flex-1",
    CardContent: "flex flex-col flex-1",
    DateText: "text-[1rem] text-[#3C3C43] font-mono",
    TitleText: "text-[1.5rem] font-mono font-bold text-black leading-tight truncate",
    CompanyText: "text-[1.125rem] text-[#3C3C43]",
    LocationText: "text-[1.125rem] text-[#0353A4] font-mono",
    FavoriteIcon: "w-[25px] h-[25px] ml-auto cursor-pointer",
    TagsRow: "flex flex-row flex-wrap gap-2 w-full",
    CategoryTag: "rounded-[100px] bg-[#3C3C43] px-3 py-1 text-md text-white font-mono",
    CriticalTag: "rounded-[100px] border border-[#FF3D00] px-3 py-1 text-md text-[#FF3D00] font-mono",
    CommonTag: "rounded-[100px] border border-[#3C3C43] px-3 py-1 text-md text-[#3C3C43] font-mono",
    CardBottom: "flex flex-row flex-wrap items-center justify-between bg-[#D9D9D9] px-4 py-3 gap-x-2 w-full",
    HideButton: "flex items-center gap-2 text-[#FF3D00] text-md sm:text-lg font-mono cursor-pointer",
    HideIcon: "w-[25px] h-[25px]",
    AddApplicationButton: "flex items-center gap-2 bg-[#0353A4] text-white px-4 py-2 rounded-lg font-mono text-md sm:text-lg font-semibold cursor-pointer",
    AddIcon: "w-[22px] h-[22px]",
    ApplyButton: "flex items-center gap-2 border border-[#0353A4] text-[#0353A4] px-4 py-2 rounded-lg font-mono text-lg font-semibold bg-white cursor-pointer",
    ApplyIcon: "w-[22px] h-[22px]",
    GroupedButtons:"ml-auto flex flex-row gap-3"
};